name: oigraph
favicon: null
layout_spectrum: 0.91032
typography_spectrum: 0.4199314534198493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e3e3'
    - '#151a14'
    - '#363d35'
    - '#8494a2'
    - '#adb5bf'
  brandStrength: 0.2718498727772385
  lightness: 0.3640214407350868
  saturation: 0.6976308431476355
  rhythmicContrast: 0.6492150197736919
purpose: []
